Modules/Member/Http/routes.php
<?php

Route::group(['middleware' => ['web', 'auth'], 'prefix' => 'home', 'namespace' => 'Modules\Member\Http\Controllers'], function () {
    Route::get('/historique', 'MemberController@historique')->name('membres.historiques');
    Route::get('/bureau', 'MemberController@bureau')->name('membres.bureaux');

    Route::get('/', 'HomeController@index')->name('home');

    Route::resource('/histories', 'HistoryController');
//    Route::resource('/posts','PostController');
    Route::resource('/objectifs', 'ObjectifController');
    Route::resource('/bureaux', 'BureauController');
    Route::resource('/calendars', 'CalendarController');
    /**
     * for the president
     */
    Route::get('/bureaux/edit_all','BureauController@editAll')->name('bureaux.edit.all');
    Route::post('/bureaux/president/{president}', 'PresidentController@update')->name('presidents.update');
    
    Route::post('/conseiller/','ConseillerController@store')->name('conseiller.store');
    Route::delete('/conseiller/{conseiller}','ConseillerController@destroy')->name('conseiller.destroy');

    Route::get('/date_creation', 'CreationDateController@index');
    Route::post('date_creation', 'CreationDateController@store')->name('date_creation.store');
    Route::put('/date_creation', 'CreationDateController@udpate')->name('date_creation.update');

    Route::resource('/fiainam-panahy', 'FiainamPanahyController');
    Route::resource('/fiombonana', 'FiombonanaController');
    Route::resource('/fitomboana', 'FitomboanaController');
    Route::resource('/tafika-masina', 'TafikaMasinaController');
    Route::resource('/maha-olona', 'MahaOlonaController');

    Route::resource('/toriteny-member', 'ToritenyController');
    Route::resource('/mahafantatra-feno-member', 'MFHController');

    Route::resource('/fiangonana-misionera-member', 'FiangonanaMisioneraController');
    Route::resource('/fampianarana-member', 'FampianaranaController');
    

    Route::resource('/vaovao-member', 'VaovaoController');

    Route::get('/perikopa', 'PerikopaController@index')->name('perikopa');
    Route::post('/perikopa', 'PerikopaController@store')->name('perikopa.store');
});

Modules/Member/Entities/Post.php
<?php

namespace Modules\Member\Entities;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = ['content', 'group_id', 'type_post_id', 'titre','hasPosts','isValid'];

    public function group()
    {
        return $this->belongsTo('App\Group');
    }

    public function type()
    {
        return $this->belongsTo('Modules\Member\Entities\TypePost');
    }

    public function comments()
    {
        return $this->hasMany('Modules\Member\Entities\Comment');
    }

    public function images()
    {
        return $this->hasMany('Modules\Member\Entities\PostImage');
    }
}

Modules/Member/Http/Controllers/FiombonanaController.php
<?php

namespace Modules\Member\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Modules\Member\Entities\Post;
use Modules\Member\Entities\TypePost;
use Modules\Member\Http\Requests\CreatePostRequest;
use Modules\Member\Http\Services\Post\PostServiceInterface;

class FiombonanaController extends Controller
{
    private $postService;
    
    protected $nbrPerPage = 5;

    protected $typeId = [12,13,14,15,16];

    public function __construct(PostServiceInterface $postService)
    {
        $this->postService = $postService;
    }

    public function index()
    {
        $posts = $this->postService->getPaginate($this->nbrPerPage, $this->typeId);
        $links = $posts->setPath('')->render();
        return view('member::posts.fiombonana.index', compact('posts','links'));
    }

    /**
     * Show the form for creating a new resource.
     * @return Response
     */
    public function create()
    {
        $types = TypePost::all()->where('type_post_id', '=', 5)->pluck('libelleType','id')->toArray();
        return view('member::posts.fiombonana.create', array('types' => $types));
    }

    /**
     * Store a newly created resource in storage.
     * @param  Request $request
     * @return Response
     */
    public function store(CreatePostRequest $request)
    {
        $this->postService->store($request);
        return redirect()->route('fiombonana.index');
    }

    /**
     * Show the specified resource.
     * @return Response
     */
    public function show($id)
    {
        $post = $this->postService->getById($id);
        return view('member::posts.fiombonana.show',compact('post'));
    }

    public function edit($id)
    {
        $post = Post::find($id);
        $types = TypePost::all()->where('type_post_id', '=', 5)->pluck('libelleType', 'id')->toArray();
        return view('member::posts.fiombonana.edit',compact('post','types'));
    }

    /**
     * Update the specified resource in storage.
     * @param  Request $request
     * @return Response
     */
    public function update(Request $request,$id)
    {
        $post = Post::find($id);
        $this->postService->update($request,$post);
        return redirect()->route('fiombonana.index');
    }

    public function destroy($id)
    {
        $this->postService->delete($id);
        return redirect()->route('fiombonana.index');
    }
}

Modules/Member/Http/Controllers/PostController.php
<?php

namespace Modules\Member\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Auth;
use Modules\Member\Entities\Post;
use Modules\Member\Http\Requests\CreatePostRequest;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function index()
    {
        $group = Auth::user()->group;
        $posts = $group->posts();
        return view('member::home.home')->with('posts');
    }

    /**
     * Store a newly created resource in storage.
     * @param  Request $request
     * @return Response
     */
    public function store(CreatePostRequest $request)
    {
        $post = new Post($request->all());
        $post->group_id = Auth::user()->group->id;
        $post->save();
        return redirect()->route('home');
    }

    /**
     * Show the specified resource.
     * @return Response
     */
    public function show($id)
    {
        $post = Post::find($id);
        return response()->json($post);
    }

    public function edit(Post $post)
    {
        return view('member::home.edit')->with('post',$post);
    }

    /**
     * Update the specified resource in storage.
     * @param  Request $request
     * @return Response
     */
    public function update(Request $request, Post $post)
    {
        $post->fill($request->all());
        $post->save();
        return redirect()->route('home');
    }

    /**
     * Remove the specified resource from storage.
     * @return Response
     */
    public function destroy(Post $post)
    {
        $post->delete();
        return redirect()->route('home');
    }
}

Modules/Member/Resources/views/posts/fiombonana/create.blade.php
@extends('member::layouts.master')
@section('section_center')
    <div class="row-col box">
        <div class="box-header">
            <h5 class="m-b-0 _300">
                Fiombonana
            </h5>
        </div>
        <div class="box-body">
            {{ Form::open( array('route' => array('fiombonana.store'),'files' => true)) }}
            {{ csrf_field() }}
            <div class="form-group row">
                <label class="col-sm-2 form-control-label">Lohateny</label>
                <div class="col-sm-10">
                    {{ Form::text('titre', '', array('class' => 'form-control','placeholder' => '','required' => true)) }}
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 form-control-label">Sokajy</label>
                <div class="col-sm-10">
                    {{ Form::select('type_post_id', $types ,null,['class' => 'form-control c-select'])  }}
                </div>
            </div>
            <div class="form-group row">
                <label for="" class="col-sm-2 form-control-label">Sehatra afaka hifampiresahana</label>
                <div class="col-sm-10 checkbox">
                    {{ Form::checkbox('hasPosts', true , true) }}
                </div>
            </div>
            <div class="form-group">
                <label>Votoantony</label>
                {{ Form::textarea('content', null , array('class' => 'form-control','rows'=> 10,'placeholder' => '','required' => true)) }}
            </div>
            <div class="form-group row">
                <label class="col-sm-2 form-control-label">Sary</label>
                <div class="col-sm-10">
                    {{ Form::file('images[]', ['multiple' => 'multiple','class'=> 'form-control']) }}
                </div>
            </div>
            <button type="submit" class="btn btn-info">Soumettre</button>
            {{ Form::close() }}
        </div>
    </div>
@endsection

Modules/Member/Resources/views/posts/fiombonana/edit.blade.php
@extends('member::layouts.master')
@section('section_center')
    <div class="row-col box">
        <div class="box-header">
            <h5 class="m-b-0 _300">
                Fiombonana
            </h5>
        </div>
        <div class="box-body">
            {{ Form::model($post, array('route' => array('fiombonana.update', $post), 'method' => 'PUT')) }}
            {{ csrf_field() }}
            <div class="form-group row">
                <label class="col-sm-2 form-control-label">Lohateny</label>
                <div class="col-sm-10">
                    {{ Form::text('titre', $post->titre, array('class' => 'form-control','placeholder' => '','required' => true)) }}
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 form-control-label">Sokajy</label>
                <div class="col-sm-10">
                    {{ Form::select('type_post_id', $types ,$post->type_post_id,['class' => 'form-control c-select'])  }}
                </div>
            </div>
            <div class="form-group row">
                <label for="" class="col-sm-2 form-control-label">Sehatra afaka hifampiresahana</label>
                <div class="col-sm-10 checkbox">
                    {{ Form::checkbox('hasPosts', null,$post->hasPosts) }}
                </div>
            </div>
            <div class="form-group">
                <label>Votoantony</label>
                {{ Form::textarea('content', $post->content , array('class' => 'form-control','rows'=> 10,'placeholder' => '','required' => true)) }}
            </div>
            <button type="submit" class="btn btn-info">Soumettre</button>
            {{ Form::close() }}
        </div>
    </div>
@endsection

Modules/Member/Resources/views/posts/fiombonana/index.blade.php
@extends('member::layouts.master')
@section('section_center')
    <div class="box">
        <div class="box-header">
            <h5 class="m-b-0 _300">Fiombonana
                <div class="btn-group pull-right">
                    <a href="{{ route('fiombonana.create') }}">
                        <button type="button" class="btn btn-sm info">Nouveau</button>
                    </a>
                </div>
            </h5>
        </div>
        <div class="box-body">
            <div class="m-b">
                @foreach($posts as $post)
                    <div class="panel box no-border m-b-xs">
                        <div class="box-header p-y-sm">
                            <div class="pull-right">
                                <div style="display: inline-flex;padding-top: 0">
                                    <a href="{{ route('fiombonana.edit',['fiombonana'=> $post]) }}"
                                       class="btn btn-xs white btn-icon"><i class="fa fa-pencil"></i>
                                    </a>
                                    {!! Form::open(['route'=> ['fiombonana.destroy', $post], 'method' => 'DELETE']) !!}
                                    <button type="submit" class="btn btn-icon btn-xs">
                                        <i class="fa fa-remove"></i>
                                    </button>
                                    {!! Form::close() !!}
                                </div>
                            </div>
                            <a href="{{ route('fiombonana.show',[ 'fiombonana' => $post->id]) }}">
                                {{ $post->titre }}
                            </a>
                        </div>
                    </div>
                @endforeach
            </div>
            {!! $links !!}
        </div>
    </div>
@endsection

Modules/Member/Resources/views/posts/fiombonana/show.blade.php
@extends('member::layouts.master')
@section('section_center')
    <div class="box">
        <div class="box-header">
            <h5 class="m-b-0 _300">Fiombonana
                <div class="btn-group pull-right">
                    <a href="{{ route('fiainam-panahy.create') }}">
                        <button type="button" class="btn btn-sm info">Nouveau</button>
                    </a>
                </div>
            </h5>
        </div>
        <div class="panel box no-border m-b-xs">
            <div class="box-header p-y-sm">
                <a data-toggle="collapse" data-parent="#accordion" data-target="#c_1">
                    {{ $post->titre }}
                </a>
            </div>
            <div id="c_1" class="collapse in">
                <div class="box-body">
                    <p class="text-sm text-muted">
                        {{ $post->content }}
                    </p>
                </div>
                <div class="">
                    @foreach($post->comments as $comment)
                        <div class="sl-item">
                            <div class="sl-content">
                                <p>{{ $comment->content }}</p>
                                <div class="sl-date text-muted pull-right">{{ $comment->updated_at }}</div>
                            </div>
                        </div>
                        <div class="box-divider"></div>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
@endsection